Models/DocumentType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibrarySystem.Models;

[Table("document_types")]
public class DocumentType
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [MaxLength(50, ErrorMessage = "The Name field must be at most {1} characters.")]
    public required string Name { get; set; }

    [Column("abbreviation")]
    [MinLength(2, ErrorMessage = "The Abbreviation field must be at least {1} characters.")]
    [MaxLength(10, ErrorMessage = "The Abbreviation field must be at most {1} characters.")]
    public required string Abbreviation { get; set; }

    [Column("description")]
    [MaxLength(300, ErrorMessage = "The Name field must be at most {1} characters.")]
    public string? Description { get; set; }
}

Models/ErrorViewModel.cs
namespace LibrarySystem.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/DocumentTypesController.cs
using LibrarySystem.Data;
using LibrarySystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;

namespace LibrarySystem.Controllers;

[Route("[controller]")]
public class DocumentTypesController : Controller
{
    private readonly ILogger<DocumentTypesController> _logger;
    private readonly ApplicationDbContext _context;



    public DocumentTypesController(ILogger<DocumentTypesController> logger, ApplicationDbContext context)
    {
        _logger = logger;
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        var allDocumentTypes = await _context.DocumentTypes.ToListAsync();
        return View(allDocumentTypes);
    }

    [Route("Find")]
    public async Task<IActionResult> Find(string keywords)
    {
        if (string.IsNullOrWhiteSpace(keywords))
        {
            return RedirectToAction(nameof(Index));
        }
        var allDocumentTypes = await _context.DocumentTypes
                                .Where(d => d.Name.Contains(keywords) ||
                                            d.Abbreviation.Contains(keywords) ||
                                            d.Description.Contains(keywords))
                                .ToListAsync();
        return View("Index", allDocumentTypes);
    }

    [Route("create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create(DocumentType documentType)
    {
        if (ModelState.IsValid)
        {
            _context.Add(documentType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        else
        {
            _logger.LogError("Error saving");
            return View(documentType);
        }
    }


    [Route("edit/{id}")]
    public async Task<IActionResult> Edit(int id)
    {
        var documentTypeFound = await _context.DocumentTypes.FindAsync(id);
        return View(documentTypeFound);
    }

    [HttpPost("edit/{id}")]
    public async Task<IActionResult> Edit(int id, DocumentType documentType)
    {
        var result = CheckExist(id);
        if (result == false)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            _context.Update(documentType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        else
        {
            _logger.LogError("El modelo no es valido");
            return View(documentType);
        }
    }


    [Route("delete/{id}")]
    public async Task<IActionResult> Delete(int id)
    {
        var documentTypeFound = await _context.DocumentTypes.FindAsync(id);
        if (documentTypeFound == null)
        {
            return NotFound();
        }
        return View(documentTypeFound);
    }

    [HttpPost("delete/{id}")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var result = CheckExist(id);
        if (result == false)
        {
            return NotFound();
        }

        var documentTypeFound = await _context.DocumentTypes.FindAsync(id);
        if (documentTypeFound == null)
        {
            return NotFound();
        }
        _context.DocumentTypes.Remove(documentTypeFound);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }



    private bool CheckExist(int id)
    {
        var checkDocumentType = _context.DocumentTypes.Any(e => e.Id == id);
        if (checkDocumentType == true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LibrarySystem.Models;

namespace LibrarySystem.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/DocumentTypes/Create.cshtml
@model DocumentType;

<h1>@ViewData["Title"]</h1>

<form asp-controller="DocumentTypes" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Abbreviation" class="control-label"></label>
        <input asp-for="Abbreviation" class="form-control" />
        <span asp-validation-for="Abbreviation" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        <a asp-controller="DocumentTypes" asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/DocumentTypes/Delete.cshtml
@model DocumentType;

<h1>@ViewData["Title"]</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Document Type</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Model.Name (@Model.Abbreviation)
        </dd>
    </dl>
    <form asp-controller="DocumentTypes" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

Views/DocumentTypes/Details.cshtml
<div class="text-center">
    <h1 class="display-4">this is the DETAILS view</h1>
</div>

Views/DocumentTypes/Edit.cshtml
@model DocumentType;

<h1>@ViewData["Title"]</h1>

<form asp-controller="DocumentTypes" asp-action="Edit" method="post">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Abbreviation" class="control-label"></label>
        <input asp-for="Abbreviation" class="form-control" />
        <span asp-validation-for="Abbreviation" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Edit" class="btn btn-primary" />
        <a asp-controller="DocumentTypes" asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/DocumentTypes/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Document Types</h1>
</div>

<nav class="navbar bg-body-tertiary container-fluid">
    <a asp-controller="DocumentTypes" asp-action="Create" class="btn btn-primary">Create</a>
    <form asp-controller="DocumentTypes" asp-action="Find" method="get" class="d-flex" role="search">
        <input class="form-control me-2" name="keywords" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</nav>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Abbreviation
            </th>
            <th>
                Description
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var element in Model)
        {
            <tr>
                <td>
                    @element.Id
                </td>
                <td>
                    @element.Name
                </td>
                <td>
                    @element.Abbreviation
                </td>
                <td>
                    @element.Description
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@element.Id" class="btn btn-info">Details</a>
                    <a asp-action="Edit" asp-route-id="@element.Id" class="btn btn-warning">Edit</a>
                    <a asp-action="Delete" asp-route-id="@element.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibrarySystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibrarySystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibrarySystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DocumentTypes" asp-action="Index">Document Types</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LibrarySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>